# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: raft.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'raft.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nraft.proto\x12\x04raft\"-\n\x0f\x43reateOperation\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t\"\x1c\n\rReadOperation\x12\x0b\n\x03key\x18\x01 \x01(\t\"-\n\x0fUpdateOperation\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t\"D\n\x0c\x43\x41SOperation\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x15\n\rexpectedValue\x18\x02 \x01(\t\x12\x10\n\x08newValue\x18\x03 \x01(\t\"\x1e\n\x0f\x44\x65leteOperation\x12\x0b\n\x03key\x18\x01 \x01(\t\"\x0f\n\rInitOperation\"\x8d\x02\n\x08LogEntry\x12\x0c\n\x04term\x18\x01 \x01(\x04\x12\'\n\x06\x63reate\x18\x02 \x01(\x0b\x32\x15.raft.CreateOperationH\x00\x12#\n\x04read\x18\x03 \x01(\x0b\x32\x13.raft.ReadOperationH\x00\x12\'\n\x06update\x18\x04 \x01(\x0b\x32\x15.raft.UpdateOperationH\x00\x12!\n\x03\x63\x61s\x18\x05 \x01(\x0b\x32\x12.raft.CASOperationH\x00\x12\'\n\x06\x64\x65lete\x18\x06 \x01(\x0b\x32\x15.raft.DeleteOperationH\x00\x12#\n\x04init\x18\x07 \x01(\x0b\x32\x13.raft.InitOperationH\x00\x42\x0b\n\toperation\"\x98\x01\n\x14\x41ppendEntriesRequest\x12\x0c\n\x04term\x18\x01 \x01(\x04\x12\x10\n\x08leaderId\x18\x02 \x01(\x04\x12\x14\n\x0cprevLogIndex\x18\x03 \x01(\x04\x12\x13\n\x0bprevLogTerm\x18\x04 \x01(\x04\x12\x1f\n\x07\x65ntries\x18\x05 \x03(\x0b\x32\x0e.raft.LogEntry\x12\x14\n\x0cleaderCommit\x18\x06 \x01(\x04\"6\n\x15\x41ppendEntriesResponse\x12\x0c\n\x04term\x18\x01 \x01(\x04\x12\x0f\n\x07success\x18\x02 \x01(\x08\"b\n\x12RequestVoteRequest\x12\x0c\n\x04term\x18\x01 \x01(\x04\x12\x13\n\x0b\x63\x61ndidateId\x18\x02 \x01(\x04\x12\x14\n\x0clastLogIndex\x18\x03 \x01(\x04\x12\x13\n\x0blastLogTerm\x18\x04 \x01(\x04\"8\n\x13RequestVoteResponse\x12\x0c\n\x04term\x18\x01 \x01(\x04\x12\x13\n\x0bvoteGranted\x18\x02 \x01(\x08\x32\x94\x01\n\x04Raft\x12H\n\rAppendEntries\x12\x1a.raft.AppendEntriesRequest\x1a\x1b.raft.AppendEntriesResponse\x12\x42\n\x0bRequestVote\x12\x18.raft.RequestVoteRequest\x1a\x19.raft.RequestVoteResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'raft_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CREATEOPERATION']._serialized_start=20
  _globals['_CREATEOPERATION']._serialized_end=65
  _globals['_READOPERATION']._serialized_start=67
  _globals['_READOPERATION']._serialized_end=95
  _globals['_UPDATEOPERATION']._serialized_start=97
  _globals['_UPDATEOPERATION']._serialized_end=142
  _globals['_CASOPERATION']._serialized_start=144
  _globals['_CASOPERATION']._serialized_end=212
  _globals['_DELETEOPERATION']._serialized_start=214
  _globals['_DELETEOPERATION']._serialized_end=244
  _globals['_INITOPERATION']._serialized_start=246
  _globals['_INITOPERATION']._serialized_end=261
  _globals['_LOGENTRY']._serialized_start=264
  _globals['_LOGENTRY']._serialized_end=533
  _globals['_APPENDENTRIESREQUEST']._serialized_start=536
  _globals['_APPENDENTRIESREQUEST']._serialized_end=688
  _globals['_APPENDENTRIESRESPONSE']._serialized_start=690
  _globals['_APPENDENTRIESRESPONSE']._serialized_end=744
  _globals['_REQUESTVOTEREQUEST']._serialized_start=746
  _globals['_REQUESTVOTEREQUEST']._serialized_end=844
  _globals['_REQUESTVOTERESPONSE']._serialized_start=846
  _globals['_REQUESTVOTERESPONSE']._serialized_end=902
  _globals['_RAFT']._serialized_start=905
  _globals['_RAFT']._serialized_end=1053
# @@protoc_insertion_point(module_scope)
